# Generated by Django 3.1.4 on 2021-01-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('id',)},
        ),
    ]
